version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
   version: 3.12
   system_packages: true
   install:
      - requirements: docs/readthedocs/requirements.txt
      - method: setuptools
        path: .

formats: []
