name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install TMalign
        run: |
          wget https://zhanggroup.org/TM-align/TMalign.cpp
          g++ -static -O3 -ffast-math -lm -o TMalign TMalign.cpp
          export PATH=$(pwd):$PATH
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest Cython
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install torch_geometric tensorflow-cpu dgl
      - name: Test with pytest
        run: |
          export PATH=$(pwd):$PATH
          pip install -r requirements.txt
          pip install coverage
          coverage run --source proteinshake -m pytest
          coverage report -m
          coverage xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: BorgwardtLab/proteinshake-v1
